export const SET_LANG = 'SET_LAN';
export const SET_INTERNET_CONNECTION = 'SET_INTERNET_CONNECTION';
export const SELECTED_TAB = 'SELECTED_TAB'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const REFRESH_LIST = 'REFRESH_LIST'
export const SELECT_TAB = 'SELECT_TAB'